language: java
dist: trusty
os: linux
addons:
  sonarcloud:
    organization: "coma123"
    token:
      secure: "fVilZ8rDtzqhxL7nEXCksKTnxdQXL2Ab5pSmpL0zZHw3zKsiKMWtuzMzIO11g+LIy6P+5sT+3ZAdcEwFeFM02R/CMpGmCIwHqNw7AvPeK8Vl6zeUEmAiV4yboIGL/7AksmSHx2nHZiQagUrLZKFhHaM3YpMmyhhbxuSxJNkZ95NPr43I5TfT7mqDWiaY/Hhmg29N8qjAO51j21j4eZwQLJIDlfnCUcGbTMHmlKsfJIuMcVPUQIE5w5rDaiMDyDdOZxlY/IKXi6JDGHP/TRthFk8zddqVj5qtzkCNKpl0K7ReMHdJb6aTSIsn6IVD+fHRev5ik2FF7HZ8DF0lC/0S62bVcmzTuF0WEWaWNre3l69dB0HBKY0GDxA4hskhVjRSMKjGKrH5Bx/LVXAo2a+U+uIO8ZmB4P7S4rwNF34ZnTke/yw7OmtesZWCDXZNzoidq59BRPL4RkkG0J1FMcWC47AsdnJC1JOX/bdunJ8Nmj2Lxil0RcLgDKK/L0La3UnNE8iKH8gE2E+rwHpKfF0wNt/mzpJYzXJ/l9DwRFyTsJoaVxDshIyM709Hp91CGy2JuNI7FeZZJK3laDmE4dHpr88MOvlPNHhvuxQG1MXUNNI1H2n1ZQlH8p9ZBgouG1LmRtY3GeyiuoSbQWmtUq4iAhb5F5G5/uHwS+BrLLNZSHo="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=coma123_Spring-Boot-Blog-REST-API

before_install:
  - chmod +x mvnw
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
