version: '3.8'
services:
  db:
    image: mysql
    container_name: blogapi-db-dev
    restart: always
    environment:
      MYSQL_DATABASE: 'blogapi'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
