name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Welcome @${{ github.actor }} to Spring-Boot-Blog-REST-API community! Thanks so much for creating your first issue :)'
          pr-message: 'Thanks so much @${{ github.actor }} for creating your first PR, the Spring-Boot-Blog-REST-API community thanks you :)'
